name = "AutoImports"
uuid = "6cdfc548-8a3a-4bf5-b37e-a5fc82b5e48c"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
